#define JOYSTICK_X_PIN F7
#define JOYSTICK_Y_PIN F6

#define JOYSTICK_CENTER 512
#define JOYSTICK_DEADZONE 200

#define UP_THRESHOLD (JOYSTICK_CENTER - JOYSTICK_DEADZONE)
#define DOWN_THRESHOLD (JOYSTICK_CENTER + JOYSTICK_DEADZONE)

