// ENCODERS
#define ENCODER_DIRECTION_FLIP
#define ENCODERS_PAD_A { B2, B2 }
#define ENCODERS_PAD_B { B3, B1 }
#define ENCODER_RESOLUTION 4

// JOYSTICK
#define JOYSTICK_X_PIN F4
#define JOYSTICK_Y_PIN F5

#define JOYSTICK_CENTER 512
#define JOYSTICK_DEADZONE 200

#define UP_THRESHOLD (JOYSTICK_CENTER - JOYSTICK_DEADZONE)
#define DOWN_THRESHOLD (JOYSTICK_CENTER + JOYSTICK_DEADZONE)

// LAYER TAPPING
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0

